deployment:
  image: docker.io/mamercad/ambientweather-exporter
  tag: latest

service:
  type: LoadBalancer
  exporter_port: 10102

secret:
  ambi_app_key: hunter2
  ambi_api_key: hunter2

influx:
  enable: false
  host: influxdb
  port: 8086
  db: ambientweather
  interval: 300
