services:

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"

  exporter:
    image: ghcr.io/mamercad/ambientweather-exporter:latest
    ports:
      - "${EXPORTER_PORT:-10102}:${EXPORTER_PORT:-10102}"
    environment:
      AMBI_APP_KEY: ${AMBI_APP_KEY}
      AMBI_API_KEY: ${AMBI_API_KEY}
      INFLUX_HOST: ${INFLUX_HOST:-influxdb}
      INFLUX_PORT: ${INFLUX_PORT:-8086}
      EXPORTER_PORT: ${EXPORTER_PORT:-10102}
