kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    deploy: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      deploy: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        deploy: "{{ .Release.Name }}"
    spec:
      containers:
        - name: ambientweather-exporter
          image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.exporter_port }}
          env:
            - name: AMBI_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-creds"
                  key: AMBI_APP_KEY
            - name: AMBI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-creds"
                  key: AMBI_API_KEY
            - name: INFLUX_HOST
              value: "{{ .Values.influx.host }}"
            - name: INFLUX_PORT
              value: "{{ .Values.influx.port }}"
            - name: INFLUX_DB
              value: "{{ .Values.influx.db }}"
            - name: EXPORTER_PORT
              value: "{{ .Values.service.exporter_port }}"
