kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    deploy: "{{ .Release.Name }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      deploy: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        deploy: "{{ .Release.Name }}"
    spec:
      containers:
        - name: ambientweather-exporter
          image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
          ports:
            - name: http
              containerPort: "{{ .Values.env.EXPORTER_PORT }}"
          env:
            - name: AMBI_APP_KEY
              value: "{{ .Values.env.AMBI_APP_KEY }}"
            - name: AMBI_API_KEY
              value: "{{ .Valuels.env.AMBI_API_KEY }}"
            - name: EXPORTER_PORT
              value: "{{ .Values.env.EXPORTER_PORT }}"
