kind: Secret
apiVersion: v1
data:
  AMBI_APP_KEY: "{{ .Values.secret.ambi_app_key | b64enc }}"
  AMBI_API_KEY: "{{ .Values.secret.ambi_app_key | b64enc }}"
metadata:
  name: "{{ .Release.Name }}-creds"
  namespace: "{{ .Release.Namespace }}"
  labels:
    deploy: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
