apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    prometheus.io/port: "{{ .Values.service.exporter_port }}"
    prometheus.io/scrape: "true"
  labels:
    deploy: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    deploy: "{{ .Release.Name }}"
  ports:
  - name: exporter
    port: {{ .Values.service.exporter_port }}
    protocol: TCP
    targetPort: {{ .Values.service.exporter_port }}
  sessionAffinity: None
  type: "{{ .Values.service.type }}"
