name: pr-testing

on:
  pull_request:

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: false

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build (no push)
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: |
            mamercad/ambientweather-exporter:pr-${{ github.event.pull_request.number }}
            ghcr.io/mamercad/ambientweather-exporter:pr-${{ github.event.pull_request.number }}
